### ISSUE TITLE
Mangle non breaking spaces

### ISSUE THREAD

**Issue by yuchi** [michael/hub#12]
Sorry if I put it here on the /hub, probably should be on /composer.

This document:

http://substance-hub.herokuapp.com/documents/35802e700ee0a9294bfbe3b2c7f3bc85

One of the paragraphs is full of `&nbsp;` instead of real spaces.

**Comment by michael** [comment]
This has been fixed already. https://github.com/substance/surface/commit/4fdae7a442a6ea4648b0e4260e22acd3c001a230

**Comment by yuchi** [comment]
Sorry! :)
