### ISSUE TITLE
Update user model and methods in users.js

### ISSUE THREAD

**Issue by michael** [michael/hub#14]
Additional fields:
- location (string)
- company (organization ?)
- website

@yuchi what's the data property for? I mean we could just store JSON in it, holding additional properties. But then we can't use SQL-Indexes.

**Comment by yuchi** [comment]
It's for non applicative data. We do not need indexes for this kind of data. A migration could change that for a field later.

EDIT: property -> field

**Comment by michael** [comment]
Agreed. :+1:
