### ISSUE TITLE
Manage db/data migrations

### ISSUE THREAD

**Issue by yuchi** [michael/hub#16]
In house solution? @vectorsize pointed me to very interesting packages.

Let's start the discussion

**Comment by michael** [comment]
Phew. No idea, I guess that's a larger discussion. But well.. I'd like to have something created by ourselves. Kind of already like the way setup.js works :)   I think we should just extend that, and come up with our own declarative syntax for migrations and only implement what we really need.

**Comment by michael** [comment]
But we may wanna tackle this after the 0.1.0 release?

**Comment by michael** [comment]
Assigned to 0.2.0 milestone. Just a thought.. we may want to store a db version number in the database. We can use that number to execute all existing migrations that are greater than that number.

**Comment by michael** [comment]
For instance:

current db version: 3

migrations:

[1] initial schema
[2] change user.name to user.username
[3] add field created_at to "documents" table.
[4] remove foreign key x
[5] add table networks
[6] add table network_memberships

**Comment by yuchi** [comment]
That's exactly how I implemented it a few months ago for a mobile app with Titanium Mobile (JS on iOS/Android).

It will be pretty trivial to port the logics (which worked flawlessly since september)

**Comment by yuchi** [comment]
I assign this issue to myself
