### ISSUE TITLE
Move to a Jekyll like blog structure

### ISSUE THREAD

**Issue by yuchi** [michael/hub#24]
We'll create .md files in a /blog directory. At startup the application will render the files and store the to serve them correctly.

**Comment by michael** [comment]
Waiit! ;)  

In around 4 weeks we'll be able to use Substance as our blog engine.. No need to setup a Jekyll workflow :)  

······································································
Michael Aufreiter
Information Design
e: michael@substance.io (mailto:michael@substance.io)
m: +43 664 1533015
w: http://substance.io
Twitter: @_mql

**Comment by yuchi** [comment]
Gosh I'm stupid sometimes.
