### ISSUE TITLE
Cover image

### ISSUE THREAD

**Issue by michael** [michael/hub#31]
Now that I'm tackling images I started wrapping my head around how we'd handle cover images, which can be specified per doc (optional).

Cover images are intended to serve for the following purposes:
- Attention (eye) catcher (e.g. on the Hub's document listing, but also on the doc itself)
- High resolution (I guess we'd like them to be high resolution so we can consider them a book cover. We need to think about nice styles when we display such documents on the hub.
- Within the composer they could work like cover images on facebook (providing a "add cover" link in the document title/abstract section.

I'll add some design sketches here. The display part for document listings can become tricky, since we need to be able to display documents /w cover next to document those that don't have one.

I'd see this as a higher priority since it will take time until people adapt it. So if we could just agree on the size I could start implementing them.

Slightly too obtrusive (too many effects) but I kind of like how the document + story cover is layed out here: http://www.nytimes.com/projects/2012/snow-fall/#/?part=tunnel-creek

**Comment by yuchi** [comment]
Oh god it's awesome!! I want it! `</spoiled>`

Imagine how better it was if the title survived the scroll :cool:

**Comment by Integral** [comment]
Fantastic! Very beautiful! Can't believe that substance might be so
fantastic
good-looking!

N.B. How can I receive some tasks to work?

**Comment by vectorsize** [comment]
It's great news that you want to help @Integral !!

We are just now working on prioritizing and trying to sort out who does what, once we know we can see how to coordinate with you.

Where you thinking of anything in particular??

**Comment by Integral** [comment]
Hello! It's great! I could try to help with hubs/nodejs stuff, ok?

**Comment by michael** [comment]
Cover images are now implemented. Closing.
