### ISSUE TITLE
Critical: refactored API endpoints

### ISSUE THREAD

**Issue by yuchi** [michael/hub#39]
In my crusade for consistency and code organization, I did a huge refactor of the APIs. Now they do look good, but are completely different, have a look 638582d67eaf90a817cac6f32d0437fc9e4af293

Michael, you'll need to change the Composer calls... sorry!

**Comment by yuchi** [comment]
BTW, I leaved the old URI in a comment before every endpoint so you'll be able to spot differences.

**Comment by michael** [comment]
Done. Closing. Let's open separate issues for follow-ups.
