### ISSUE TITLE
OAuth Impl

### ISSUE THREAD

**Issue by yuchi** [michael/hub#4]
I'm leaving the `master` branch for the `oauth` branch, to implement all the infrastructure for oauth.

Once done we'll merge to the visual changes I see you (@michael) are doing. See you soon on master :)

Is it ok?

**Comment by michael** [comment]
Perfect. :)

On 14.01.2013, at 03:34, Pier Paolo Ramon notifications@github.com wrote:

I'm leaving the master branch for the oauth branch, to implement all the
infrastructure for oauth.

Once done we'll merge to the visual changes I see you
(@michaelhttps://github.com/michael)
are doing. See you soon on master :)

Is it ok?

—
Reply to this email directly or view it on
GitHubhttps://github.com/michael/hub/issues/4.
