### ISSUE TITLE
Limit results in APIs

### ISSUE THREAD

**Issue by yuchi** [michael/hub#42]
This is a big challenge.

The HTTP `Link` Header should be sent. Queries in data accessors must accept limits and offset (of course), `db.many` should take into account the limit and return specialized information.

``` js
// faked syncronous calls

function userDocuments (username, limit, offset) {
  if (limit == null) {
    limit = db.DEFAULT_LIMIT;
    offset = 0;
  } else if (offset == null) {
    offset = 0;
  }

  // attion to the `+ 1`!
  var results = db.query(USER_DOCUMENTS_SQL, limit + 1, offset);

  var count = results.length;

  var response = {
    results: results.slice(0, limit);
  };

  if (count > limit) {
    response.next = {
      limit: limit,
      offset: offset + limit
    };
  }

  if (offset > 0) {
    response.prev = {
      limit: limit,
      offset: Math.max(0, offset - limit)
    }
  }

  return response;
}
```

An augmented array could also act as an array for our internal use.

**Comment by michael** [comment]
Yeah I know. But let's postpone that for now. However one thought I had is giving away API keys on a per request basis. So we can ensure the API is not abused.

**Comment by michael** [comment]
@yuchi I was about to write up the API docs. I guess we should give away API keys on a per request basis so we don't need to worry our API is being abused. Also we can get in touch better with potential Substance users.

**Comment by michael** [comment]
If you agree, pls open up a new ticket.

**Comment by yuchi** [comment]
I agree. I'm scared by "/users" :)

**Comment by michael** [comment]
scared by "/users"? ;)

**Comment by yuchi** [comment]
It will be a big json :)

**Comment by yuchi** [comment]
Closing for obsolescence
