### ISSUE TITLE
Code out of sync

### ISSUE THREAD

**Issue by vectorsize** [michael/hub#48]
The pused code seems to be out of sync, somehow a table documents in the db is missing and [this version of setup.js](https://github.com/michael/hub/blob/70a91ee053d32316db58f2a20b58f493fce720ed/lib/setup.js) that was supposed to create it is totally gone, we need to have a working codebase in one of the branches so that each of us can work on it.

@yuchi could you please take a look at this?

**Comment by yuchi** [comment]
I crossed the streams with @michael during a refactor. I'll review the changes tomorrow afternoon and fix this up. Thanks @vectorsize to pointing me to this.

**Comment by yuchi** [comment]
Update: my goal for tomorrow evening is to have a **full** testsuite for the publication flow, exactly for this kind of things.

**Comment by michael** [comment]
Cool. Please run a test against an empty db to see if seeding the db works.

**Comment by vectorsize** [comment]
@michael I did empty the db several times already and same happens. There's nowhere in the code where the table documents is being created anymore.

@yuchi that would be great! I would like anyhow to coordinate with you the work on the hub to know what each of us is doing

**Comment by vectorsize** [comment]
finally working!! thanks :)
