### ISSUE TITLE
users.create

### ISSUE THREAD

**Issue by michael** [michael/hub#6]
Add validations on the serverside.
- check username format, email format, etc.
- check if username exists
- return proper error object like `{errors: [{field: "username", "message": "Username already exists"}]}`

I have not looked into the passport stuff yet. Maybe this offers some functionality.

@yuchi do you have time to take care of this?

**Comment by yuchi** [comment]
Sure, if you do not mind I'll work on it once main oauth stuff is done.

**Comment by michael** [comment]
Sure. Just wondering: Is there a use-case for regular OAuth already?

I guess you just wanna share functionality, and implement `/authenticate` on top of the OAuth code?

**Comment by yuchi** [comment]
Validation is done, horribly executed, but works. At the moment there's no formatting of the errors on the API side.

**Comment by michael** [comment]
That's great. I had this on my todolist :)

Can you look into #10? That's a critical one.. And I have no idea ;)

**Comment by yuchi** [comment]
It's my next one :)

**Comment by michael** [comment]
Yeah. ! :) My next one is this: Supply an optional name for a document (using the settings dialog) so users can access their docs using a pretty URL (USERNAME/DOCNAME).

-> http://substance.io/michael/substance

**Comment by michael** [comment]
Just tried creating a new user. It fails silently. Will investigate more tomorrow. Could be a regression related to newly added validation stuff.

**Comment by yuchi** [comment]
As I said there's no formatting of the errors. Where did it fail? API or POST to  /signup?

**Comment by michael** [comment]
API side: POST to /register

Hotfixing some composer stuff, that's why I'm just capturing hub issues without looking into the details (->tomorrow)
