### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by michael** [michael/hub#68]
Victor had that problem when executing `./update.sh`.

```
[ 37%] Building CXX object app/osx/CMakeFiles/Substance.dir/appDelegate.mm.o
/Users/vectorsize/Dropbox/Documents/Substance/repos/substance/composer/app/osx/appDelegate.mm:64:106: error: expected method to read array element not
      found on object of type 'NSArray *'
      url = [NSString stringWithFormat: @"file://%@/Contents/Assets/test.html?testname=%@", pathEscaped, arguments[idx]];
                                                                                                         ^
1 error generated.
make[2]: *** [app/osx/CMakeFiles/Substance.dir/appDelegate.mm.o] Error 1
make[1]: *** [app/osx/CMakeFiles/Substance.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by obuchtala** [comment]
This is actually obsolete as we integrated the test.
However, i don't have a clue what objective-shit is talking about...
I'll fix it later.
Am 01.05.2013 11:20 schrieb "Michael Aufreiter" notifications@github.com:

**Comment by vectorsize** [comment]
In [this stackoverflow](http://stackoverflow.com/questions/11425976/compiler-error-expected-method-not-found-when-using-subscript-on-nsarray) comment it says:

> You've got to be compiling with the OS X 10.8 SDKs -- otherwise Foundation objects don't have the necessary methods for the subscripting bit of the literal syntax.*

I have OSX 10.7.5 that might be something…

**Comment by obuchtala** [comment]
Done by victor.
